// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611172222_AdicionarSubtarefas")]
    partial class AdicionarSubtarefas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TodoApi.Subtarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarefaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("Subtarefas");
                });

            modelBuilder.Entity("TodoApi.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#6366f1",
                            Nome = "Trabalho"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#a855f7",
                            Nome = "Estudos"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#ec4899",
                            Nome = "Pessoal"
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#14b8a6",
                            Nome = "Casa"
                        });
                });

            modelBuilder.Entity("TodoApi.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataFim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UrgenciaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UrgenciaId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("TodoApi.Urgencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prazo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urgencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = "bg-primary",
                            Cor = "#007bff",
                            Descricao = "Não Urgente",
                            Prazo = "24 dias"
                        },
                        new
                        {
                            Id = 2,
                            Classe = "bg-success",
                            Cor = "#198754",
                            Descricao = "Pouco Urgente",
                            Prazo = "12 dias"
                        },
                        new
                        {
                            Id = 3,
                            Classe = "bg-warning",
                            Cor = "#ffc107",
                            Descricao = "Urgente",
                            Prazo = "6 dias"
                        },
                        new
                        {
                            Id = 4,
                            Classe = "bg-orange",
                            Cor = "#fd7e14",
                            Descricao = "Muito Urgente",
                            Prazo = "1 dia"
                        },
                        new
                        {
                            Id = 5,
                            Classe = "bg-danger",
                            Cor = "#dc3545",
                            Descricao = "Imediato",
                            Prazo = "Imediato"
                        });
                });

            modelBuilder.Entity("TodoApi.Subtarefa", b =>
                {
                    b.HasOne("TodoApi.Tarefa", "Tarefa")
                        .WithMany("Subtarefas")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("TodoApi.Tarefa", b =>
                {
                    b.HasOne("TodoApi.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");

                    b.HasOne("TodoApi.Urgencia", "Urgencia")
                        .WithMany()
                        .HasForeignKey("UrgenciaId");

                    b.Navigation("Tag");

                    b.Navigation("Urgencia");
                });

            modelBuilder.Entity("TodoApi.Tarefa", b =>
                {
                    b.Navigation("Subtarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
