// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701182452_TornarUrgenciaIdOpcional")]
    partial class TornarUrgenciaIdOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TodoApi.Anotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoFolha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Anotacoes");
                });

            modelBuilder.Entity("TodoApi.Habito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Habitos");
                });

            modelBuilder.Entity("TodoApi.RegistroHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabitoId");

                    b.ToTable("RegistroHabitos");
                });

            modelBuilder.Entity("TodoApi.Subtarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarefaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("Subtarefas");
                });

            modelBuilder.Entity("TodoApi.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#6366f1",
                            Nome = "Trabalho",
                            Tipo = "kanban"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#a855f7",
                            Nome = "Estudos",
                            Tipo = "kanban"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#3b82f6",
                            Nome = "Faculdade",
                            Tipo = "kanban"
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#ec4899",
                            Nome = "Pessoal",
                            Tipo = "kanban"
                        },
                        new
                        {
                            Id = 5,
                            Cor = "#14b8a6",
                            Nome = "Casa",
                            Tipo = "kanban"
                        },
                        new
                        {
                            Id = 6,
                            Cor = "#22c55e",
                            Nome = "Financeiro",
                            Tipo = "financeiro"
                        });
                });

            modelBuilder.Entity("TodoApi.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataFim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UrgenciaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UrgenciaId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("TodoApi.TransacaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("TransacoesFinanceiras");
                });

            modelBuilder.Entity("TodoApi.Urgencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prazo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urgencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = "bg-primary",
                            Cor = "#007bff",
                            Descricao = "Não Urgente",
                            Prazo = "24 dias"
                        },
                        new
                        {
                            Id = 2,
                            Classe = "bg-success",
                            Cor = "#198754",
                            Descricao = "Pouco Urgente",
                            Prazo = "12 dias"
                        },
                        new
                        {
                            Id = 3,
                            Classe = "bg-warning",
                            Cor = "#ffc107",
                            Descricao = "Urgente",
                            Prazo = "6 dias"
                        },
                        new
                        {
                            Id = 4,
                            Classe = "bg-orange",
                            Cor = "#fd7e14",
                            Descricao = "Muito Urgente",
                            Prazo = "1 dia"
                        },
                        new
                        {
                            Id = 5,
                            Classe = "bg-danger",
                            Cor = "#dc3545",
                            Descricao = "Imediato",
                            Prazo = "Imediato"
                        });
                });

            modelBuilder.Entity("TodoApi.Anotacao", b =>
                {
                    b.HasOne("TodoApi.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TodoApi.Habito", b =>
                {
                    b.HasOne("TodoApi.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TodoApi.RegistroHabito", b =>
                {
                    b.HasOne("TodoApi.Habito", "Habito")
                        .WithMany("Registros")
                        .HasForeignKey("HabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");
                });

            modelBuilder.Entity("TodoApi.Subtarefa", b =>
                {
                    b.HasOne("TodoApi.Tarefa", "Tarefa")
                        .WithMany("Subtarefas")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("TodoApi.Tarefa", b =>
                {
                    b.HasOne("TodoApi.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");

                    b.HasOne("TodoApi.Urgencia", "Urgencia")
                        .WithMany()
                        .HasForeignKey("UrgenciaId");

                    b.Navigation("Tag");

                    b.Navigation("Urgencia");
                });

            modelBuilder.Entity("TodoApi.TransacaoFinanceira", b =>
                {
                    b.HasOne("TodoApi.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TodoApi.Habito", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("TodoApi.Tarefa", b =>
                {
                    b.Navigation("Subtarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
